[auth]
redirect_uri = "https://YouthProfile.streamlit.app/oauth2callback"
cookie_secret = "y4j-volunteer-...your-random-32-char-string"
client_id = "5148...apps.googleusercontent.com"
client_secret = "GOCSPX-..."
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

# ADD THIS SECTION FOR THE  DRIVE SCOPE
[auth.client_kwargs]
scope = "openid profile email https://www.googleapis.com/auth/drive.file"
