[auth]
redirect_uri = "https://YouthProfile.streamlit.app/oauth2callback"
cookie_secret = "y4j-volunteer-...your-random-32-char-string"
client_id = "5148...apps.googleusercontent.com"
client_secret = "GOCSPX-..."
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"

[google_auth]
client_id = "1234567890-your-client-id.apps.googleusercontent.com"
client_secret = "GOCSPX-your-client-secret"
refresh_token = "1//0-your-long-refresh-token-string"

# ADD THIS SECTION FOR THE  DRIVE SCOPE
[auth.client_kwargs]
scope = "openid profile email https://www.googleapis.com/auth/drive.file"

[gcp_service_account]
type = "service_account"
project_id = "..."
private_key_id = "..."
private_key = "..."
client_email = "..."
client_id = "..."
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "..."
